//
// Created by nathan on 05/02/16.
//

#ifndef RUBKIS_MOVES_H
#define RUBKIS_MOVES_H

#endif //RUBKIS_MOVES_H

/*
 * This is a enum that contains the definition of possible moves
 */

enum moves{TOP_CLOCKWISE, TOP_ANTICLOCKWISE, RIGHT_CLOCKWISE, RIGHT_ANTICLOCKWISE, LEFT_CLOCKWISE, LEFT_ANTICLOCKWISE,
            BOTTOM_CLOCKWISE, BOTTOM_ANTICLOCKWISE, FRONT_CLOCKWISE, FRONT_ANTICLOCKWISE, BACK_CLOCKWISE, BACK_ANTICLOCKWISE };